site_name: Stevedev7
site_url: https://stevedev7.github.io/mkdocs-101/
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: "#"